#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : xcursorgen
Version  : 1.0.7
Release  : 12
URL      : http://xorg.freedesktop.org/releases/individual/app/xcursorgen-1.0.7.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/app/xcursorgen-1.0.7.tar.gz
Source99 : http://xorg.freedesktop.org/releases/individual/app/xcursorgen-1.0.7.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : HPND
Requires: xcursorgen-bin = %{version}-%{release}
Requires: xcursorgen-license = %{version}-%{release}
Requires: xcursorgen-man = %{version}-%{release}
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xorg-macros)

%description
xcursorgen prepares X11 cursor sets for use with libXcursor.
All questions regarding this software should be directed at the
Xorg mailing list:

%package bin
Summary: bin components for the xcursorgen package.
Group: Binaries
Requires: xcursorgen-license = %{version}-%{release}

%description bin
bin components for the xcursorgen package.


%package license
Summary: license components for the xcursorgen package.
Group: Default

%description license
license components for the xcursorgen package.


%package man
Summary: man components for the xcursorgen package.
Group: Default

%description man
man components for the xcursorgen package.


%prep
%setup -q -n xcursorgen-1.0.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557103871
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557103871
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xcursorgen
cp COPYING %{buildroot}/usr/share/package-licenses/xcursorgen/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xcursorgen

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xcursorgen/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xcursorgen.1
