#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : xcursorgen
Version  : 1.0.8
Release  : 14
URL      : https://www.x.org/releases/individual/app/xcursorgen-1.0.8.tar.gz
Source0  : https://www.x.org/releases/individual/app/xcursorgen-1.0.8.tar.gz
Source1  : https://www.x.org/releases/individual/app/xcursorgen-1.0.8.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : HPND
Requires: xcursorgen-bin = %{version}-%{release}
Requires: xcursorgen-license = %{version}-%{release}
Requires: xcursorgen-man = %{version}-%{release}
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
xcursorgen prepares X11 cursor sets for use with libXcursor.
All questions regarding this software should be directed at the
Xorg mailing list:

%package bin
Summary: bin components for the xcursorgen package.
Group: Binaries
Requires: xcursorgen-license = %{version}-%{release}

%description bin
bin components for the xcursorgen package.


%package license
Summary: license components for the xcursorgen package.
Group: Default

%description license
license components for the xcursorgen package.


%package man
Summary: man components for the xcursorgen package.
Group: Default

%description man
man components for the xcursorgen package.


%prep
%setup -q -n xcursorgen-1.0.8
cd %{_builddir}/xcursorgen-1.0.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1670223846
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1670223846
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xcursorgen
cp %{_builddir}/xcursorgen-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xcursorgen/32b0302709046c7d107587b2a4435e91bcea2be8
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xcursorgen

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xcursorgen/32b0302709046c7d107587b2a4435e91bcea2be8

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xcursorgen.1
